version: "3"

services:
  tg_ss_gpt:
    container_name: tg_ss_gpt
    build: ./
    command: >
      sh -c "python3 main.py"
    depends_on:
      - db_tg_ss_gpt
    network_mode: host
    volumes:
      - .:/apps/core
    env_file:
      - .env

  db_tg_ss_gpt:
    image: postgres:15-alpine
    container_name: db_tg_ss_gpt
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    env_file:
      - .env

volumes:
  pgdata: